# Generated by Django 5.2.8 on 2025-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('no_hp', models.CharField(max_length=15, verbose_name='Nomor HP')),
            ],
        ),
    ]
