# Generated by Django 5.2.8 on 2025-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lapangan', models.CharField(max_length=100, verbose_name='Nama Lapangan')),
                ('harga_per_jam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga per Jam')),
            ],
        ),
    ]
