# Generated by Django 5.2.8 on 2025-11-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0002_lapangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='harga_per_jam',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='nama_lapangan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_hp',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.lapangan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.pelanggan')),
            ],
        ),
    ]
