# Generated by Django 5.2.8 on 2025-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0003_alter_lapangan_harga_per_jam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
